### PR TITLE
Sukh final changes

### PR DESCRIPTION
**Pull request by sukhpreetp**
Fixed UI for edit profile
Added logout and edit profile buttons for users logged in:
Image 15189
Image 15190

### CODE REVIEW

**Comment by UTS-JKok** [comment]
I would prefer users can logout from the home screen, what do you think? I'm okay with how the modal looks but the icon to switch back to light mode is impossible to see sometimes.

Ignoring how logout button navigates to SubmissionConfirm since I don't believe we have a logout function atm.

**Comment by UTS-JKok** [comment]
Speaking again on user exposed by AuthContext, its values are either undefined (default) or true (user is logged-in). The latter is a definite value because user is explicitly being set to true in this instance, but when you're checking if a user is not logged-in I would avoid checking against undefined, since we don't enforce this value anywhere. It could easily be null, which isn't the same. I would just negate the check on if they are logged-in, which is what the code you copied from me is doing.

**Review by TheerthaS — APPROVED** [review]
I agree with Jun that we should be able to log out from home screen. Otherwise the modal and buttons look good to me

**Review by UTS-JKok — APPROVED** [review]
Looks good as long as we exclude logging-out from HomePage.

**Pull request merged**
