### PR TITLE
Navigation Attempt 1

### PR DESCRIPTION
**Pull request by sukhpreetp**
@TheerthaS can you please check if this still works as required? I have tried changing the entire code for appnavigator.js so that you can access login & register pages from homepage

------------------
Trying to fix the navigation

### CODE REVIEW

**Comment by UTS-JKok** [comment]
Login page appears to be broken because previous navigation was dependent on the value of user in AuthProvider.js. The simplest solution is simply to force navigation once the user has been verified; see the example change on Discord.

**Comment by sukhpreetp** [comment]
@UTS-JKok @TheerthaS I have tried to connect all screens. Please approve if it is all good. If I have missed anything then let me know

**Comment by UTS-JKok** [comment]
SubmissionConfirm connects to HomePage but nothing connects to SubmissionConfirm, please update.

**Review by UTS-JKok — CHANGES_REQUESTED** [review]
Nothing connects to SubmissionConfirm, please update.

**Comment by sukhpreetp** [comment]
> Nothing connects to SubmissionConfirm, please update.

The screen that connects to SubmissionConfirm is pending design

**Review by UTS-JKok — APPROVED** [review]

**Review by TheerthaS — APPROVED** [review]

**Pull request merged**
